# Generated by Django 3.1.7 on 2021-03-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_label', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.CharField(max_length=50)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('text_body', models.CharField(max_length=250)),
                ('text_source', models.CharField(max_length=250)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_name', models.CharField(max_length=45)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('voice_recording', models.CharField(max_length=3000)),
                ('voice_edited', models.BooleanField(default=False)),
                ('voice_privacy', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapi.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapi.text')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('comment_edited', models.BooleanField(default=False)),
                ('comment_detail', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapi.voice')),
            ],
        ),
    ]
